FROM ubuntu:20.04

# Locale
ENV LANG C.UTF-8

# Prerequisites
RUN apt-get update && apt-get install -y \
    curl \
    git \
    unzip \
    xz-utils \
    zip \
    libglu1-mesa \
    openjdk-11-jdk \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Install Flutter
RUN git clone https://github.com/flutter/flutter.git -b stable --depth 1 /usr/local/flutter
ENV PATH $PATH:/usr/local/flutter/bin:/usr/local/flutter/bin/cache/dart-sdk/bin

# Install Android SDK
RUN wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip \
    && unzip commandlinetools-linux-6609375_latest.zip -d /usr/local/android-sdk \
    && rm commandlinetools-linux-6609375_latest.zip
ENV ANDROID_SDK_ROOT /usr/local/android-sdk
ENV PATH $PATH:/usr/local/android-sdk/tools/bin:/usr/local/android-sdk/platform-tools:/usr/local/android-sdk/commandlinetools/bin
RUN yes | sdkmanager --licenses
RUN sdkmanager "platform-tools" "platforms;android-33" "build-tools;30"
